### ISSUE TITLE
RAML 1.0 types not recognized

### ISSUE THREAD

**Issue by rscarson** [mulesoft/raml-sublime-plugin#9]
Types as defined in the RAML 1.0 specs are not being recognized.
example can be seen [here](https://github.com/raml-org/raml-examples/blob/master/typesystem/complex.raml)

Minimal example to reproduce:

```
#%RAML 1.0
title: Test
types:
  Test:
    type: object
    properties:
      id: string
      type: string
```

```#%RAML 1.0 DataType``` header not being recognized either
